language: python

cache: pip

matrix:

  include:

    - python: 3.3

    - python: 3.5

    - python: 3.5-dev

    - python: nightly

  allow_failures:

    - python: 3.5-dev

    - python: nightly

# command to install dependencies

before_install: cp config/headlights.cfg.test config/headlights.cfg

install:

    - pip install -r requirements.txt

    - pip install codecov

# command to run tests

script: nosetests runtests.py --with-coverage

after_success: codecov
